version: "3.9"
services:
  db:
    image: postgres:12
    restart: unless-stopped
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    expose:
      - "5432" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5432:5432" # Use this for local development on host machine
  bot:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    depends_on:
      - db
    restart: always